// The is an example to create a binray for key inseation and deleting.
// It is simple enough to store the beakpoint information.
// This code is generated by chatgpt.

#ifndef __MAP_H__
#define __MAP_H__

#include <stdio.h>
#include <stdlib.h>

enum Color { RED, BLACK };

typedef struct Node {
    int data;
    enum Color color;
    struct Node *left, *right, *parent;
} Node;

void insertNode(Node **root, int data);
Node* findNode(Node *root, int data);
void deleteNode(Node **root, int data);

#endif // __MAP_H__

