// The is an example to create a binray for key inseation and deleting.
// It is simple enough to store the beakpoint information.
// This code is generated by chatgpt.

#ifndef __MAP_H__
#define __MAP_H__

#include <stdio.h>
#include <stdlib.h>

typedef struct TreeNode {
    int data;
    struct TreeNode *left;
    struct TreeNode *right;
} TreeNode;

// Function to insert a new node in the binary tree
void insert(TreeNode **root, int data);

// Function to find a node with given data in the binary tree
TreeNode* find(TreeNode *root, int data);

// Function to delete a node from the binary tree
TreeNode* delete(TreeNode *root, int data);

#endif // __MAP_H__

