rv32c        ?= 0
rv32e        ?= 0
rv32b        ?= 0
TARGET_SIM   ?= "$(ROOT_SRV32)/sim/sim +trace"
TARGET_SWSIM ?= $(ROOT_SRV32)/tools/rvsim
TARGET_FLAGS ?= $(RISCV_TARGET_FLAGS) -q
ifeq ($(shell command -v $(TARGET_SIM) 2> /dev/null),)
    $(error Target simulator executable '$(TARGET_SIM)` not found)
endif

RISCV_PREFIX   ?= riscv64-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_READELF  ?= $(RISCV_PREFIX)readelf

ifeq ($(rv32b),1)
BEXTS          ?= _zba_zbb_zbc_zbs
endif

ifeq ($(rv32c),1)
ifeq ($(rv32e),1)
RISCV_GCC_OPTS ?= -static -march=rv32emac_zicsr -mabi=ilp32e $(EXTRA_CFLAGS) -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)
else
RISCV_GCC_OPTS ?= -static -march=rv32imac_zicsr$(BEXTS) -mabi=ilp32 $(EXTRA_CFLAGS) -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)
endif
else
ifeq ($(rv32e),1)
RISCV_GCC_OPTS ?= -static -march=rv32em_zicsr -mabi=ilp32e $(EXTRA_CFLAGS) -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)
else
RISCV_GCC_OPTS ?= -static -march=rv32im_zicsr$(BEXTS) -mabi=ilp32 $(EXTRA_CFLAGS) -mcmodel=medany -g -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)
endif
endif

COMPILE_CMD=\
	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
		-I$(ROOTDIR)/riscv-test-suite/env/ \
		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
		-T$(TARGETDIR)/$(RISCV_TARGET)/env/link.ld $$< \
		-o $$@

OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
		  $$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
		  $$(RISCV_READELF) -a $$@ > $$@.readelf

COMPILE_TARGET=\
		$(COMPILE_CMD); \
        if [ $$$$? -ne 0 ] ; \
            then \
            echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
            exit 1 ; \
        fi ; \
		$(OBJ_CMD); \
        if [ $$$$? -ne 0 ] ; \
            then \
            echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
            exit 1 ; \
        fi ;

RUN_CMD=\
	$(TARGET_SIM)

RUN_TARGET=\
	$(RUN_CMD) $(TARGET_FLAGS) $(*).elf $< 2> $@; mv trace.log $(*).trace.log; \
	mv dump.txt $(*).signature.output; if [ -f coverage.dat ]; then mv coverage.dat $(*)_cov.dat; fi; \
	$(TARGET_SWSIM) -l $(*).trace_sw.log $(TARGET_FLAGS) $(*).elf $< 2> $@; \
	diff --brief $(*).trace.log $(*).trace_sw.log

